import {
  Truck,
  ShieldCheck,
  RefreshCw,
  Award,
  Heart,
  Star,
  Zap,
  Package,
  CreditCard,
  Clock,
  ThumbsUp,
  Gift,
  Leaf,
  Lock,
  Headphones,
  Sparkles,
  type LucideIcon,
} from 'lucide-react';

export const ICON_MAP: Record<string, LucideIcon> = {
  truck: Truck,
  shield: ShieldCheck,
  refresh: RefreshCw,
  award: Award,
  heart: Heart,
  star: Star,
  zap: Zap,
  package: Package,
  creditCard: CreditCard,
  clock: Clock,
  thumbsUp: ThumbsUp,
  gift: Gift,
  leaf: Leaf,
  lock: Lock,
  headphones: Headphones,
  sparkles: Sparkles,
};

export const ICON_FIELD_OPTIONS = [
  { label: 'None', value: '' },
  { label: 'Truck (shipping)', value: 'truck' },
  { label: 'Shield (guarantee)', value: 'shield' },
  { label: 'Refresh (returns)', value: 'refresh' },
  { label: 'Award (quality)', value: 'award' },
  { label: 'Heart (favorite)', value: 'heart' },
  { label: 'Star (rating)', value: 'star' },
  { label: 'Zap (fast)', value: 'zap' },
  { label: 'Package (delivery)', value: 'package' },
  { label: 'Credit card (payment)', value: 'creditCard' },
  { label: 'Clock (support hours)', value: 'clock' },
  { label: 'Thumbs up (satisfaction)', value: 'thumbsUp' },
  { label: 'Gift (bonus)', value: 'gift' },
  { label: 'Leaf (eco-friendly)', value: 'leaf' },
  { label: 'Lock (secure)', value: 'lock' },
  { label: 'Headphones (support)', value: 'headphones' },
  { label: 'Sparkles (new)', value: 'sparkles' },
];
